apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstack-gateway-controller
  labels:
    app.kubernetes.io/name: openstack-gateway-controller
    app.kubernetes.io/part-of: gateway-api-openstack
